apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:5432
    user: ${POSTGRES_USER}
    isDefault: false
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "require"
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
